name: CI/CD Pipeline - Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application to EKS
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: us-east-1

      # 3. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Apply Terraform Configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # 6. Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "1.27.0"

      # 7. Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "3.12.0"

      # 8. Update kubeconfig for EKS
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name hotel-event-cluster

      # 9. Log in to DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 10. Deploy Auth Service
      - name: Deploy Auth Service
        run: |
          helm upgrade --install auth-service ./helm/auth-service \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/auth-service \
            --set image.tag=latest \
            --set env.JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --set env.DATABASE_URL=${{ secrets.DATABASE_URL }}

      # 11. Deploy Event Service
      - name: Deploy Event Service
        run: |
          helm upgrade --install event-service ./helm/event-service \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/event-service \
            --set image.tag=latest \
            --set env.DATABASE_URL=${{ secrets.DATABASE_URL }}

      # 12. Deploy Notification Service
      - name: Deploy Notification Service
        run: |
          helm upgrade --install notification-service ./helm/notification-service \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/notification-service \
            --set image.tag=latest \
            --set env.EMAIL_SERVICE_API_KEY=${{ secrets.EMAIL_SERVICE_API_KEY }}

      # 13. Deploy Payment Service
      - name: Deploy Payment Service
        run: |
          helm upgrade --install payment-service ./helm/payment-service \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/payment-service \
            --set image.tag=latest \
            --set env.PAYMENT_GATEWAY_URL=${{ secrets.PAYMENT_GATEWAY_URL }}
