services:
  mysql-auth:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_auth
    ports:
      - "3307:3306"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  mysql-system:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_system
    ports:
      - "3306:3306"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s 

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: hotel_system
    ports:
      - "5432:5432"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - hotel-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - hotel-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel-network

  analytics-service:
    build: ./backend/domains/analytics/analytics-service
    ports:
      - "3008:3008"
    networks:
      - hotel-network

  auth-service:
    build: ./backend/domains/authentication/auth-service
    ports:
      - "3001:3001"
    networks:
      - hotel-network

  billing-service:
    build: ./backend/domains/booking/billing-service
    ports:
      - "3015:3015"
    networks:
      - hotel-network

  booking-service:
    build: ./backend/domains/booking/booking-service
    ports:
      - "3004:3004"
    networks:
      - hotel-network

  customer-engagement-service:
    build: ./backend/domains/customer-engagement
    ports:
      - "3004:3004"
    networks:
      - hotel-network

  email-service:
    build: ./backend/domains/customer-engagement/email-service
    ports:
      - "3012:3012"
    networks:
      - hotel-network

  event-service:
    build: ./backend/domains/customer-engagement/event-service
    ports:
      - "3022:3022"
    networks:
      - hotel-network

  feedback-service:
    build: ./backend/domains/customer-engagement/feedback-service
    ports:
      - "3010:3010"
    networks:
      - hotel-network

  file-storage-service:
    build: ./backend/domains/analytics/file-storage-service
    ports:
      - "3019:3019"
    networks:
      - hotel-network

  inventory-service:
    build: ./backend/domains/analytics/inventory-service
    ports:
      - "3009:3009"
    networks:
      - hotel-network

  loyalty-service:
    build: ./backend/domains/customer-engagement/loyalty-service
    ports:
      - "3017:3017"
    networks:
      - hotel-network

  notification-preferences-service:
    build: ./backend/domains/authentication/notification-preferences-service
    ports:
      - "3011:3011"
    networks:
      - hotel-network

  notification-service:
    build: ./backend/domains/customer-engagement/notification-service
    ports:
      - "3003:3003"
    networks:
      - hotel-network

  payment-gateway-service:
    build: ./backend/domains/booking/payment-gateway-service
    ports:
      - "3023:3023"
    networks:
      - hotel-network

  payment-service:
    build: ./backend/domains/booking/payment-service
    ports:
      - "3005:3005"
    networks:
      - hotel-network

  reporting-service:
    build: ./backend/domains/analytics/reporting-service
    ports:
      - "3014:3014"
    networks:
      - hotel-network

  review-service:
    build: ./backend/domains/customer-engagement/review-service
    ports:
      - "3007:3007"
    networks:
      - hotel-network

  room-service:
    build: ./backend/domains/booking/room-service
    ports:
      - "3013:3013"
    networks:
      - hotel-network

  scheduler-service:
    build: ./backend/domains/booking/scheduler-service
    ports:
      - "3018:3018"
    networks:
      - hotel-network

  support-service:
    build: ./backend/domains/customer-engagement/support-service
    ports:
      - "3016:3016"
    networks:
      - hotel-network

  user-profile-service:
    build: ./backend/domains/authentication/user-profile-service
    ports:
      - "3006:3006"
    networks:
      - hotel-network

volumes:
  mongodb_data:

networks:
  hotel-network:
    driver: bridge
