services:
  user-profile-service:
    build: ./backend/domains/authentication/user-profile-service
    ports:
      - "3006:3006"
    networks:
      - hotel-network

  auth-service:
    build: ./backend/domains/authentication/auth-service
    ports:
      - "3001:3001"
    networks:
      - hotel-network

  notification-preferences-service:
    build: ./backend/domains/authentication/notification-preferences-service
    ports:
      - "3011:3011"
    networks:
      - hotel-network

  booking-service:
    build: ./backend/domains/booking/booking-service
    ports:
      - "3004:3004"
    networks:
      - hotel-network

  payment-service:
    build: ./backend/domains/booking/payment-service
    ports:
      - "3005:3005"
    networks:
      - hotel-network

  payment-gateway-service:
    build: ./backend/domains/booking/payment-gateway-service
    ports:
      - "3023:3023"
    networks:
      - hotel-network

  room-service:
    build: ./backend/domains/booking/room-service
    ports:
      - "3013:3013"
    networks:
      - hotel-network

  scheduler-service:
    build: ./backend/domains/booking/scheduler-service
    ports:
      - "3018:3018"
    networks:
      - hotel-network

  analytics-service:
    build: ./backend/domains/analytics/analytics-service
    ports:
      - "3008:3008"
    networks:
      - hotel-network

  inventory-service:
    build: ./backend/domains/analytics/inventory-service
    ports:
      - "3009:3009"
    networks:
      - hotel-network

  reporting-service:
    build: ./backend/domains/analytics/reporting-service
    ports:
      - "3014:3014"
    networks:
      - hotel-network

  file-storage-service:
    build: ./backend/domains/analytics/file-storage-service
    ports:
      - "3019:3019"
    networks:
      - hotel-network

  email-service:
    build: ./backend/domains/customer-engagement/email-service
    ports:
      - "3012:3012"
    networks:
      - hotel-network

  event-service:
    build: ./backend/domains/customer-engagement/event-service
    ports:
      - "3022:3022"
    networks:
      - hotel-network

  feedback-service:
    build: ./backend/domains/customer-engagement/feedback-service
    ports:
      - "3010:3010"
    networks:
      - hotel-network

  loyalty-service:
    build: ./backend/domains/customer-engagement/loyalty-service
    ports:
      - "3017:3017"
    networks:
      - hotel-network

  notification-service:
    build: ./backend/domains/customer-engagement/notification-service
    ports:
      - "3003:3003"
    networks:
      - hotel-network

  review-service:
    build: ./backend/domains/customer-engagement/review-service
    ports:
      - "3007:3007"
    networks:
      - hotel-network

  support-service:
    build: ./backend/domains/customer-engagement/support-service
    ports:
      - "3016:3016"
    networks:
      - hotel-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge
