version: "3.8"

services:
  mysql-auth:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_auth
    ports:
      - "3307:3306"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  mysql-system:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_system
    ports:
      - "3306:3306"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: hotel_system
    ports:
      - "5432:5432"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql-system
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    depends_on:
      mysql-system:
        condition: service_healthy
    networks:
      - hotel-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - hotel-network

  auth-service:
    build: ./domains/authentication/auth-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql-auth
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotel_auth
    depends_on:
      mysql-auth:
        condition: service_healthy
    networks:
      - hotel-network

  user-profile-service:
    build: ./domains/authentication/user-profile-service
    ports:
      - "3006:3006"
    environment:
      - DB_HOST=mysql-auth
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotel_auth
    depends_on:
      mysql-auth:
        condition: service_healthy
    networks:
      - hotel-network

  notification-preferences-service:
    build: ./domains/authentication/notification-preferences-service
    ports:
      - "3011:3011"
    environment:
      - DB_HOST=mysql-auth
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotel_auth
    depends_on:
      mysql-auth:
        condition: service_healthy
    networks:
      - hotel-network

  booking-service:
    build: ./domains/booking/booking-service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=mysql-system
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotel_bookings
    depends_on:
      mysql-system:
        condition: service_healthy
    networks:
      - hotel-network

  payment-service:
    build: ./domains/booking/payment-service
    ports:
      - "3005:3005"
    environment:
      - DB_HOST=mysql-system
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotel_payments
      - STRIPE_SECRET_KEY=sk_test_example
    depends_on:
      mysql-system:
        condition: service_healthy
    networks:
      - hotel-network

  email-service:
    build: ./domains/customer-engagement/email-service
    ports:
      - "3012:3012"
    environment:
      - EMAIL_USER=your-email@example.com
      - EMAIL_PASS=your-email-password
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
    networks:
      - hotel-network

  analytics-service:
    build: ./domains/analytics/analytics-service
    ports:
      - "3008:3008"
    environment:
      - DB_HOST=mysql-system
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotel_analytics
    depends_on:
      mysql-system:
        condition: service_healthy
    networks:
      - hotel-network

  file-storage-service:
    build: ./domains/analytics/file-storage-service
    ports:
      - "3019:3019"
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=your_bucket_name
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge
