version: "3.8"

services:
  auth-service:
    image: myrepo/auth-service:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - hotel-network

  event-service:
    image: myrepo/event-service:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - hotel-network

  notification-service:
    image: myrepo/notification-service:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - EMAIL_SERVICE_API_KEY=${EMAIL_SERVICE_API_KEY}
    networks:
      - hotel-network

  payment-service:
    image: myrepo/payment-service:latest
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PAYMENT_GATEWAY_URL=${PAYMENT_GATEWAY_URL}
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge
