version: "3.8"
services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-service
      - JWT_SECRET=development_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
