version: "3.8"

services:
  # MongoDB
  mongo:
    image: mongo:5.0
    container_name: dev-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  # Redis
  redis:
    image: redis:6.2
    container_name: dev-redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

  # Microservicios
  analytics-service:
    build:
      context: ./services/analytics-service
    ports:
      - "3008:3008"
    depends_on:
      - mongo
    networks:
      - backend-network

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    networks:
      - backend-network

  billing-service:
    build:
      context: ./services/billing-service
    ports:
      - "3015:3015"
    depends_on:
      - mongo
    networks:
      - backend-network

  booking-service:
    build:
      context: ./services/booking-service
    ports:
      - "3004:3004"
    depends_on:
      - mongo
    networks:
      - backend-network

  email-service:
    build:
      context: ./services/email-service
    ports:
      - "3012:3012"
    networks:
      - backend-network

  event-service:
    build:
      context: ./services/event-service
    ports:
      - "3022:3022"
    depends_on:
      - mongo
    networks:
      - backend-network

  feedback-service:
    build:
      context: ./services/feedback-service
    ports:
      - "3010:3010"
    depends_on:
      - mongo
    networks:
      - backend-network

  file-storage-service:
    build:
      context: ./services/file-storage-service
    ports:
      - "3019:3019"
    volumes:
      - file-uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - backend-network

  inventory-service:
    build:
      context: ./services/inventory-service
    ports:
      - "3009:3009"
    depends_on:
      - mongo
    networks:
      - backend-network

  loyalty-service:
    build:
      context: ./services/loyalty-service
    ports:
      - "3017:3017"
    depends_on:
      - mongo
    networks:
      - backend-network

  notification-preferences-service:
    build:
      context: ./services/notification-preferences-service
    ports:
      - "3011:3011"
    depends_on:
      - mongo
    networks:
      - backend-network

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    networks:
      - backend-network

  payment-gateway-service:
    build:
      context: ./services/payment-gateway-service
    ports:
      - "3023:3023"
    depends_on:
      - mongo
    networks:
      - backend-network

  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    networks:
      - backend-network

  reporting-service:
    build:
      context: ./services/reporting-service
    ports:
      - "3014:3014"
    depends_on:
      - mongo
    networks:
      - backend-network

  review-service:
    build:
      context: ./services/review-service
    ports:
      - "3007:3007"
    depends_on:
      - mongo
    networks:
      - backend-network

  room-service:
    build:
      context: ./services/room-service
    ports:
      - "3013:3013"
    depends_on:
      - mongo
    networks:
      - backend-network

  scheduler-service:
    build:
      context: ./services/scheduler-service
    ports:
      - "3018:3018"
    depends_on:
      - mongo
    networks:
      - backend-network

  support-service:
    build:
      context: ./services/support-service
    ports:
      - "3016:3016"
    depends_on:
      - mongo
    networks:
      - backend-network

  user-profile-service:
    build:
      context: ./services/user-profile-service
    ports:
      - "3006:3006"
    depends_on:
      - mongo
    networks:
      - backend-network

volumes:
  mongo-data:
  file-uploads:

networks:
  backend-network:
    driver: bridge

