version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/usr/src/app
    command: ["npm", "run", "start"]

  backend:
    build:
      context: ..
    ports:
      - "4000:4000"
    env_file:
      - ./dev.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
