version: "3.8"

services:
  # MongoDB
  mongo:
    image: mongo:5.0
    container_name: prod-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  # Redis
  redis:
    image: redis:6.2
    container_name: prod-redis
    networks:
      - backend-network

  # Microservicios
  analytics-service:
    build:
      context: ./services/analytics-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/analytics-db

  auth-service:
    build:
      context: ./services/auth-service
    depends_on:
      - mongo
      - redis
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=prodsecret

  billing-service:
    build:
      context: ./services/billing-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/billing-db

  booking-service:
    build:
      context: ./services/booking-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/booking-db

  email-service:
    build:
      context: ./services/email-service
    networks:
      - backend-network
    environment:
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=587
      - SMTP_USER=your_user
      - SMTP_PASS=your_password

  event-service:
    build:
      context: ./services/event-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/event-db

  feedback-service:
    build:
      context: ./services/feedback-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/feedback-db

  file-storage-service:
    build:
      context: ./services/file-storage-service
    volumes:
      - file-uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/file-storage-db

  inventory-service:
    build:
      context: ./services/inventory-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory-db

  loyalty-service:
    build:
      context: ./services/loyalty-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/loyalty-db

  notification-preferences-service:
    build:
      context: ./services/notification-preferences-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/notification-preferences-db

  notification-service:
    build:
      context: ./services/notification-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/notification-db

  payment-gateway-service:
    build:
      context: ./services/payment-gateway-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment-gateway-db

  payment-service:
    build:
      context: ./services/payment-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment-db

  reporting-service:
    build:
      context: ./services/reporting-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/reporting-db

  review-service:
    build:
      context: ./services/review-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/review-db

  room-service:
    build:
      context: ./services/room-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/room-db

  scheduler-service:
    build:
      context: ./services/scheduler-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/scheduler-db

  support-service:
    build:
      context: ./services/support-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/support-db

  user-profile-service:
    build:
      context: ./services/user-profile-service
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-profile-db

volumes:
  mongo-data:
  file-uploads:

networks:
  backend-network:
    driver: bridge
