name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          for service in auth-service event-service notification-service booking-service payment-service \
                        user-profile-service review-service analytics-service inventory-service feedback-service \
                        notification-preferences-service reporting-service audit-log-service support-ticket-service \
                        email-service file-upload-service notification-queue-service payment-gateway-service \
                        customer-support-service scheduler-service; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./services/$service
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
          done
