name: Build, Push, and Deploy Inventory-Service

on:
  push:
    branches: [ "qa" ]
    paths:
      - "backend/domains/analytics/inventory-service/**"  # Se activa cuando hay cambios en esta carpeta

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest ./backend/domains/analytics/inventory-service/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOSTINVENTORY }} << 'EOF'
        # 1) Actualizar sistema e instalar Docker si no está presente
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Crear el archivo .env en EC2 con las credenciales de la BD
        echo "DB_HOST=${{ secrets.DB_HOSTINVENTORY }}" > .env
        echo "DB_USER=${{ secrets.DB_USERINVENTORY }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSINVENTORY }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAMEINVENTORY }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORTINVENTORY }}" >> .env

        # 3) Detener y eliminar contenedor previo
        sudo docker stop inventory-container || true
        sudo docker rm inventory-container || true

        # 4) Descargar nueva imagen de Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest

        # 5) Ejecutar el contenedor con el .env
        sudo docker run -d --env-file .env -p 3009:3009 --name inventory-container ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest

        # 6) Limpiar imágenes antiguas
        sudo docker image prune -f
        EOF

