name: Build, Push, and Deploy File-Storage-Service

on:
  push:
    branches: [ "qa" ]
    paths:
      - "backend/domains/analytics/file-storage-service/**"  # Se activa si hay cambios en esta carpeta

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/file-storage-service:latest ./backend/domains/analytics/file-storage-service/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-storage-service:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOSTANALITYCS }} << 'EOF'
        # 1) Actualizar sistema e instalar Docker si no está presente
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Generar el archivo .env en el servidor EC2
        echo "STORAGE_PATH=${{ secrets.STORAGE_PATH }}" > .env
        echo "PORT=${{ secrets.FILE_STORAGE_PORT }}" >> .env

        # 3) Detener y eliminar contenedor previo
        sudo docker stop file-storage-container || true
        sudo docker rm file-storage-container || true

        # 4) Descargar nueva imagen de Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/file-storage-service:latest

        # 5) Ejecutar el contenedor con el .env
        sudo docker run -d --env-file .env -p 3019:3019 --name file-storage-container ${{ secrets.DOCKERHUB_USERNAME }}/file-storage-service:latest

        # 6) Limpiar imágenes antiguas
        sudo docker image prune -f
        EOF
