name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t auth-service .
          docker tag auth-service:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest

      - name: Build and Push Docker Image
        run: |
          docker build -t user-profile-service .
          docker tag user-profile-service:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/user-profile-service:latest
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/user-profile-service:latest

      - name: Build and Push Docker Image
        run: |
          docker build -t notification-preferences-service .
          docker tag notification-preferences-service:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/notification-preferences-service:latest
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/notification-preferences-service:latest