name: Build, Push, and Deploy Reporting-Service

on:
  push:
    branches: [ "qa" ]
    paths:
      - "backend/domains/analytics/reporting-service/**"  # Se ejecuta cuando hay cambios en esta carpeta

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reporting-service:latest ./backend/domains/analytics/reporting-service/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/reporting-service:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOSTREPORTING }} << 'EOF'
        # 1) Actualizar sistema e instalar Docker si no está presente
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Crear archivo .env en el servidor EC2
        echo "DB_HOST=${{ secrets.DB_HOSTREPORTING }}" > .env
        echo "DB_USER=${{ secrets.DB_USERREPORTING }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSREPORTING }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAMEREPORTING }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORTREPORTING }}" >> .env

        # 3) Detener y eliminar contenedor previo
        sudo docker stop reporting-container || true
        sudo docker rm reporting-container || true

        # 4) Descargar la nueva imagen desde Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reporting-service:latest

        # 5) Ejecutar el contenedor con el .env
        sudo docker run -d --env-file .env -p 3014:3014 --name reporting-container ${{ secrets.DOCKERHUB_USERNAME }}/reporting-service:latest

        # 6) Limpiar imágenes antiguas
        sudo docker image prune -f
        EOF
